config/routes.rb
Rails.application.routes.draw do

  get 'scenes/index'

  get 'scenes/show'

  get 'scenes/new'

  get 'scenes/create'

  get 'scenes/update'

  get 'scenes/edit'

  devise_for :users

  root 'welcome#index'

  resources :adventures, only: [ :index, :new, :show, :create ]
  resources :scenes, only: [ :new, :create ]

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  has_many :scenes
  belongs_to :user

  default_scope { order("created_at desc") }
  scope :published, -> { where(published: true) }

  validates_presence_of :title
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :scene
  has_one :next_scene, class_name: 'Scene'
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :adventure
  has_many :choices
  accepts_nested_attributes_for :choices
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :adventures
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :new, :create ]

  def index
    @adventures = current_user.adventures
  end

  def new
    @adventure = Adventure.new
  end

  def show
    @adventure = Adventure.find(params[:id])
  end

  def create
    @adventure = Adventure.new(adventure_params)

    if @adventure.save
      redirect_to @adventure, notice: 'Your adventure has been created successfully.'
    else
      render action: :new
    end
  end

  private
  def adventure_params
    params.require(:adventure).permit(:title, :author, :description, :user_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    adventures_path
  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :update, :edit, :index ]

  def index
  end

  def show
  end

  def new
    @scene = Scene.new(adventure_id: params[:adventure_id])
  end

  def create
  end

  def update
  end

  def edit
  end

  private
  def scene_params
    params.require(:scene).permit(:content, :adventure_id, choices_attributes: [:id, :content, :_destroy])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @adventures = Adventure.published.all
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper

  def adventure_description(adventure)
    adventure.description || 'There is no description available for this adventure.'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/adventures/_adventure.html.haml
.col-md-4
  %h2= link_to adventure.title, adventure_path(adventure)
  %h3= "By  " + adventure.author
  %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  %p
    = link_to 'View details »', adventure_path(adventure), class: 'btn btn-secondary', role: 'button'

app/views/adventures/index.html.haml
.container.top-page-margin
  .row
    = render @adventures

app/views/adventures/new.html.haml
.container.top-page-margin
  .row
    .col-sm-8.col-sm-offset-2
      .card.card-block
        %h4.card-title Create Adventure
        %p.card-text
          = simple_form_for @adventure do |f|
            = f.input :title, placeholder: 'Enter Title'
            = f.input :author, placeholder: "Enter Author's Name"
            = f.input :description, placeholder: 'Enter Adventure Description', as: :text, :input_html => {:rows => 6}
            = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
            = f.button :submit, class: 'form-control btn btn-success'

app/views/adventures/show.html.haml
.container.top-page-margin
  .row
    %h1= @adventure.title
    %p= @adventure.author
    %p= adventure_description(@adventure)
    %hr
    %h2.inline-heading Scenes
    = link_to 'Add New Scene', new_scene_path( adventure_id: @adventure.id ), class: 'btn btn-primary'
    = render(:partial => 'scenes/scene', :collection => @adventure.scenes) || content_tag( :p, 'This adventure has no scenes yet.')

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AdventureBuilder
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    / The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
  %body
    %nav.navbar.navbar-static-top.navbar-dark.bg-inverse
      %a.navbar-brand{:href => "/"} AdventureBuilder
      %ul.nav.navbar-nav
        - if current_user
          %li.nav-item
            = link_to "My Adventures", adventures_path, class: 'nav-link'
          %li.nav-item
            = link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            %a.nav-link{:href => "/users/sign_in"} Login
    / Main jumbotron for a primary marketing message or call to action

    = yield

    %hr/
    %footer
      .container
        %p.text-xs-right © Jeremy Samples 2016

app/views/scenes/_scene.html.haml
%p
  = scene.content

app/views/scenes/create.html.haml
%h1 Scenes#create
%p Find me in app/views/scenes/create.html.haml

app/views/scenes/edit.html.haml
%h1 Scenes#edit
%p Find me in app/views/scenes/edit.html.haml

app/views/scenes/index.html.haml
%h1 Scenes#index
%p Find me in app/views/scenes/index.html.haml

app/views/scenes/new.html.haml
.container.top-page-margin
  .row
    = simple_nested_form_for @scene do |f|
      -# = f.input :name, placeholder: 'Enter Name (Not for reader display)'
      = f.input :content, placeholder: 'Enter Scene Content Here', as: :text, :input_html => { :rows => 20 }
      = f.input :adventure_id, :as => :hidden
      = f.fields_for :choices do |choice_form|
        = choice_form.link_to_remove "Remove this choice", class: 'float-it-right'
        = choice_form.input :content
      %p= f.link_to_add "Add a choice", :choices
      = f.button :submit, class: 'form-control btn btn-success'

app/views/scenes/show.html.haml
%h1 Scenes#show
%p Find me in app/views/scenes/show.html.haml

app/views/scenes/update.html.haml
%h1 Scenes#update
%p Find me in app/views/scenes/update.html.haml

app/views/welcome/index.html.haml
.jumbotron
  .container
    %h1.display-3 Hello, world!
    %p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
    %p
      %a.btn.btn-primary.btn-lg{:href => "#", :role => "button"} Learn more »
.container
  / Example row of columns
  .row
    = render @adventures